#pragma kernel CSGetDeltas
#pragma kernel CSScan
#pragma kernel CSAggregate

StructuredBuffer<uint> _Input;
uint _InputLength;

RWStructuredBuffer<uint> _Result;

uint GetByte(uint byteIndex)
{
    uint shift = (byteIndex % 4) * 8;
    uint byte = (_Input[byteIndex / 4] >> shift) & 0xFF; // isolate 1-byte chunks
    byte = byte - 48; // convert ASCII digits to base 10
    // 0-9 = 0-9
    // L = 28
    // R = 34
    // newline = 4294967258

    return byte;
}

RWStructuredBuffer<uint> _Deltas;
RWStructuredBuffer<uint> _DeltasB;

[numthreads(32,1,1)]
void CSGetDeltas (uint3 id : SV_DispatchThreadID)
{
    uint byteIndex = id.x;
    uint totalBytes = _InputLength * 4;
    
    if (byteIndex >= totalBytes)
        return;
    
    uint byte = GetByte(byteIndex);

    // if the selected byte is a newline, calculate all the deltas (looking backwards)
    if (!(byte & 0x10000000))
        return;

    uint currentNumber = 0;
    uint power = 1;
    for (int i = 1; i < 5; i++)
    {
        uint nextByte = GetByte(byteIndex - i);
        if (nextByte == 28)
        {
            // dial pointed left/negative, flip sign
            currentNumber = -currentNumber; 
            break;
        }
        else if (nextByte == 34)
        {
            // dial pointed right
            break;
        }
        else
        {
            currentNumber += nextByte * power;
            power *= 10;
        }
    }
    
    _Deltas[byteIndex] = currentNumber;
}

uint _Stride;

// very very inefficient, should be using something better like:
// https://developer.nvidia.com/gpugems/gpugems3/part-vi-gpu-computing/chapter-39-parallel-prefix-sum-scan-cuda
[numthreads(32,1,1)]
void CSScan (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    uint totalBytes = _InputLength * 4;
    
    if (index >= totalBytes)
        return;
    
    int value = _Deltas[index];
    
    if (index >= _Stride)
    {
        value += _Deltas[index - _Stride]; 
    }
    
    _DeltasB[index] = value;
}

int GetFinalValue(uint index)
{
    int value = _Deltas[index];
    
    // get actual final value - dial should start at 50, and loops over
    int finalValue = (50 + value) % 100;
    
    return finalValue;
}

[numthreads(32,1,1)]
void CSAggregate (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    uint totalBytes = _InputLength * 4;
    
    if (index >= totalBytes)
        return;
    
    int finalValue = GetFinalValue(index);
    int previousFinalValue = GetFinalValue(index - 1);
    
    // because of how our sparse array works, we should only count the first instance of each "dial is zeroed out"
    if (finalValue == 0 && finalValue != previousFinalValue)
    {
        InterlockedAdd(_Result[0], 1);
    }
}
